### ISSUE TITLE
"Undefined method" for every iteration of setup_and_run

### ISSUE THREAD

**Issue by JustinFarris** [MongoHQ/newrelic-mongodb-agent#15]
Each time the metrics are pulled and reported, the log file throws this out:

```
undefined method `[]' for nil:NilClass: mongodb_agent.rb:128:in `block in report_lock_counter_metric'
   mongodb_agent.rb:128:in `each'
   mongodb_agent.rb:128:in `inject'
   mongodb_agent.rb:128:in `report_lock_counter_metric'
   mongodb_agent.rb:71:in `poll_cycle'
   /var/lib/gems/2.1.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/agent.rb:139:in `run'
   /var/lib/gems/2.1.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:143:in `block in run_agent_data_collection'
   /var/lib/gems/2.1.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:141:in `each'
   /var/lib/gems/2.1.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:141:in `run_agent_data_collection'
   /var/lib/gems/2.1.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:127:in `loop_forever'
   /var/lib/gems/2.1.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:15:in `setup_and_run'
   mongodb_agent.rb:150:in `<module:MongodbAgent>'
   mongodb_agent.rb:9:in `<main>'
```

I suspect it might be due to an update to the newrelic_plugin gem, and thus also related to issue #14

**Comment by gmcinnes** [comment]
I"m seeing this too. Let me know if you need help diagnosing.

**Comment by chromerobv** [comment]
any news on this? basically all the calls that are 'report_lock_counter_metric' throw this error.

**Comment by demobox** [comment]
I'm getting not quite the same, but a very similar error because some of the metrics the agent expects are simply not reported in my instance - specifically, the cursor metrics. Adding the appropriate:

```
if stats['cursor']
...
end
```

makes the error go away for me.
